### ISSUE TITLE
请问一下微调的时候出现这个怎么处理“ModuleNotFoundError: No module named 'sat.model.finetune.lora_mixin'”，学生党租的算力平台，不太懂部署这一块有没有做对

### ISSUE THREAD

**Issue by minlo-18** [THUDM/VisualGLM-6B#120]
root@autodl-container-9ed51187fa-29111776:~/autodl-tmp# bash finetune/finetune_visualglm.sh
NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 deepspeed --master_port 16666 --hostfile hostfile_single finetune_visualglm.py --experiment-name finetune-visualglm-6b --model-parallel-size 1 --mode finetune --train-iters 300 --resume-dataloader --max_source_length 64 --max_target_length 256 --lora_rank 10 --pre_seq_len 4 --train-data ./fewshot-data/dataset.json --valid-data ./fewshot-data/dataset.json --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 300 --eval-interval 10000 --save ./checkpoints --split 1 --eval-iters 10 --eval-batch-size 8 --zero-stage 1 --lr 0.0001 --batch-size 20 --skip-init --fp16 --use_lora
Setting ds_accelerator to cuda (auto detect)
[2023-06-08 15:58:22,720] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-06-08 15:58:22,766] [INFO] [runner.py:555:main] cmd = /root/miniconda3/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=16666 --enable_each_rank_log=None finetune_visualglm.py --experiment-name finetune-visualglm-6b --model-parallel-size 1 --mode finetune --train-iters 300 --resume-dataloader --max_source_length 64 --max_target_length 256 --lora_rank 10 --pre_seq_len 4 --train-data ./fewshot-data/dataset.json --valid-data ./fewshot-data/dataset.json --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 300 --eval-interval 10000 --save ./checkpoints --split 1 --eval-iters 10 --eval-batch-size 8 --zero-stage 1 --lr 0.0001 --batch-size 20 --skip-init --fp16 --use_lora
Setting ds_accelerator to cuda (auto detect)
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NCCL_IB_DISABLE=0
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NCCL_NET_GDR_LEVEL=2
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.9.6-1+cuda11.3
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.9.6-1
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NCCL_P2P_DISABLE=1
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NCCL_VERSION=2.9.6-1
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.9.6-1+cuda11.3
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-06-08 15:58:24,247] [INFO] [launch.py:138:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.9.6-1
[2023-06-08 15:58:24,248] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-06-08 15:58:24,248] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-06-08 15:58:24,248] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-06-08 15:58:24,248] [INFO] [launch.py:163:main] dist_world_size=1
[2023-06-08 15:58:24,248] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "finetune_visualglm.py", line 9, in <module>
    from sat.model.finetune.lora_mixin import LoraMixin
ModuleNotFoundError: No module named 'sat.model.finetune.lora_mixin'
[2023-06-08 15:58:27,257] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 1649
[2023-06-08 15:58:27,257] [ERROR] [launch.py:320:sigkill_handler] ['/root/miniconda3/bin/python', '-u', 'finetune_visualglm.py', '--local_rank=0', '--experiment-name', 'finetune-visualglm-6b', '--model-parallel-size', '1', '--mode', 'finetune', '--train-iters', '300', '--resume-dataloader', '--max_source_length', '64', '--max_target_length', '256', '--lora_rank', '10', '--pre_seq_len', '4', '--train-data', './fewshot-data/dataset.json', '--valid-data', './fewshot-data/dataset.json', '--distributed-backend', 'nccl', '--lr-decay-style', 'cosine', '--warmup', '.02', '--checkpoint-activations', '--save-interval', '300', '--eval-interval', '10000', '--save', './checkpoints', '--split', '1', '--eval-iters', '10', '--eval-batch-size', '8', '--zero-stage', '1', '--lr', '0.0001', '--batch-size', '20', '--skip-init', '--fp16', '--use_lora'] exits with return code = 1

**Comment by 1049451037** [comment]
你对代码做修改了吗，代码里是直接`from lora_mixin import LoraMixin`的，没有用到sat

**Comment by 1049451037** [comment]
另外sat里的lora文件改名为lora2了，`from sat.model.finetune.lora2 import LoraMixin`

**Comment by minlo-18** [comment]
> 另外sat里的lora文件改名为lora2了，`from sat.model.finetune.lora2 import LoraMixin`

感谢您的帮助，我重新拉了一下git就有了，但是目前又遇到一个很难受的问题，微调下载的东西在root/.cache里，但是我那个只有14g，而那个包解压后有15.6G，想知道如何让微调下载的包能在python代码里改路径，谢谢大佬啦！

**Comment by 1049451037** [comment]
sat的cache应该在/root/.sat_models目录下，可以通过设置`SAT_HOME=/your/dir`来改变下载路径，你说的root/.cache应该是huggingface的cache吧，可是微调并不支持huggingface，我记得huggingface也有类似的环境变量

**Comment by minlo-18** [comment]
> SAT_HOME=

请问一下这个SAT_HOME=参数是要在哪个python脚本里修改，是加到哪行cmd命令里么

**Comment by minlo-18** [comment]
> 你说的root/.cache应该是huggingface的cache吧

类似的~ 我是下载在root后解压不开来，然后挪开后去解压

**Comment by 1049451037** [comment]
```
SAT_HOME=/your/dir python run.py
或者
SAT_HOME=/your/dir bash script.sh
```

**Comment by minlo-18** [comment]
> ```
> SAT_HOME=/your/dir python run.py
> 或者
> SAT_HOME=/your/dir bash script.sh
> ```

好像还是不太行 刚才试了一下， emmm想请问一下 他去下载visualglm-6b.zip之后，是解压到了哪个目录吖，我尝试在root那个盘删点东西 然后把解压后的挪进去看看

**Comment by minlo-18** [comment]
我在 bash finetune/finetune_visualglm.sh 的时候他会给我下载 visualglm-6b.zip(13.4G)，然后会进行解压，解压的时候就显示空间不足了，现在我的处理是把这个zip挪另一个盘，解压后14.5G，有个叫visualglm-6b的文件夹，这个文件夹要挪到哪里去可以被它训练的时候读取到呢，谢谢老哥啦！

**Comment by minlo-18** [comment]
这个问题应该是由于我把 tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True) 改成了 tokenizer = AutoTokenizer.from_pretrained("models--THUDM--visualglm-6b/snapshots/f4f759acde0926fefcd35e2c626e08adb452eff8", trust_remote_code=True)造成的
修改回去就好了
现在应该是在微调中吧？
![image](https://github.com/THUDM/VisualGLM-6B/assets/60054647/2f853901-b31a-4ab8-8351-696adc369e36)

**Comment by minlo-18** [comment]
不能windows微调还是太不方便了_(:3_/ 没一会儿我另一个盘又满了 唉

**Comment by 1049451037** [comment]
windows是可以微调的，只要安装deepspeed

**Comment by minlo-18** [comment]
感谢老哥的帮助！ 昨天在autoDL上成功跑通了微调，也跑出模型来了，20多张 300步 lora微调 用A100大概微调15分钟左右能好，就是还没调出预期的想法，还在犹豫到底是增加训练样本对呢还是 增加步数_(:3_/  非常感谢老哥的帮助啦！接下来想去研究一下怎么在windows部署deepspeed
