### ISSUE TITLE
用A100 80G显存跑的微调报显存不足

### ISSUE THREAD

**Issue by smallhackeryifa** [THUDM/VisualGLM-6B#164]
训练相关参数

NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 deepspeed --master_port 16666 --include localhost:0 --hostfile hostfile_single finetune_visualglm.py --experiment-name finetune-visualglm-6b --model-parallel-size 1 --mode finetune --train-iters 10 --resume-dataloader --max_source_length 32 --max_target_length 128 --lora_rank 10 --layer_range 0 14 --pre_seq_len 2 --train-data ./fewshot-data/dataset.json --valid-data ./fewshot-data/dataset.json --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 300 --eval-interval 10000 --save ./checkpoints --split 1 --eval-iters 10 --eval-batch-size 1 --zero-stage 1 --lr 0.0001 --batch-size 1 --gradient-accumulation-steps 4 --skip-init --fp16 --use_qlora
可以帮忙看下原因吗？看README中说的16G左右就可以跑微调

**Comment by smallhackeryifa** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 29.06 GiB (GPU 0; 79.35 GiB total capacity; 72.66 GiB already allocated; 5.65 GiB free; 72.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by 1049451037** [comment]
能给出更具体的报错信息吗？我这里是可以正常跑的。或者检查一下你的显卡有没有其他程序在跑，nvidia-smi看一下不跑程序的时候多少显存空闲。

**Comment by smallhackeryifa** [comment]
NCCL_DEBUG=info NCCL_IB_DISABLE=0 NCCL_NET_GDR_LEVEL=2 deepspeed --master_port 16666 --include localhost:0 --hostfile hostfile_single finetune_visualglm.py --experiment-name finetune-visualglm-6b --model-parallel-size 1 --mode finetune --train-iters 10 --resume-dataloader --max_source_length 32 --max_target_length 128 --lora_rank 10 --layer_range 0 14 --pre_seq_len 2 --train-data ./fewshot-data/dataset.json --valid-data ./fewshot-data/dataset.json --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 300 --eval-interval 10000 --save ./checkpoints --split 1 --eval-iters 10 --eval-batch-size 1 --zero-stage 1 --lr 0.0001 --batch-size 1 --gradient-accumulation-steps 4 --skip-init --fp16 --use_qlora
[2023-07-06 16:23:28,962] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-06 16:23:29,293] [WARNING] [runner.py:196:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-07-06 16:23:29,300] [INFO] [runner.py:555:main] cmd = /root/miniconda3/envs/visualglm-6b/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=16666 --enable_each_rank_log=None finetune_visualglm.py --experiment-name finetune-visualglm-6b --model-parallel-size 1 --mode finetune --train-iters 10 --resume-dataloader --max_source_length 32 --max_target_length 128 --lora_rank 10 --layer_range 0 14 --pre_seq_len 2 --train-data ./fewshot-data/dataset.json --valid-data ./fewshot-data/dataset.json --distributed-backend nccl --lr-decay-style cosine --warmup .02 --checkpoint-activations --save-interval 300 --eval-interval 10000 --save ./checkpoints --split 1 --eval-iters 10 --eval-batch-size 1 --zero-stage 1 --lr 0.0001 --batch-size 1 --gradient-accumulation-steps 4 --skip-init --fp16 --use_qlora
[2023-07-06 16:23:30,313] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-06 16:23:30,641] [INFO] [launch.py:138:main] 0 NCCL_DEBUG=info
[2023-07-06 16:23:30,641] [INFO] [launch.py:138:main] 0 NCCL_NET_GDR_LEVEL=2
[2023-07-06 16:23:30,641] [INFO] [launch.py:138:main] 0 NCCL_IB_DISABLE=0
[2023-07-06 16:23:30,641] [INFO] [launch.py:145:main] WORLD INFO DICT: {'localhost': [0]}
[2023-07-06 16:23:30,641] [INFO] [launch.py:151:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-07-06 16:23:30,641] [INFO] [launch.py:162:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-07-06 16:23:30,641] [INFO] [launch.py:163:main] dist_world_size=1
[2023-07-06 16:23:30,641] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-07-06 16:23:32,136] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-07-06 16:23:32,863] [WARNING] Failed to load bitsandbytes:No module named 'bitsandbytes'
[2023-07-06 16:23:32,872] [INFO] using world size: 1 and model-parallel size: 1 
[2023-07-06 16:23:32,872] [INFO] > padded vocab (size: 100) with 28 dummy tokens (new size: 128)
[2023-07-06 16:23:32,874] [INFO] [RANK 0] > initializing model parallel with size 1
[2023-07-06 16:23:32,875] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-07-06 16:23:32,875] [INFO] [comm.py:594:init_distributed] cdb=None
[2023-07-06 16:23:32,875] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter cpu_offload is deprecated use offload_optimizer instead
[2023-07-06 16:23:32,875] [INFO] [checkpointing.py:764:_configure_using_config_file] {'partition_activations': False, 'contiguous_memory_optimization': False, 'cpu_checkpointing': False, 'number_checkpoints': None, 'synchronize_checkpoint_boundary': False, 'profile': False}
[2023-07-06 16:23:32,876] [INFO] [checkpointing.py:226:model_parallel_cuda_manual_seed] > initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/torch/nn/init.py:405: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:05<00:00,  1.13s/it]
iZ2ze7iugkwh6c0dul6ed3Z:14094:14094 [0] NCCL INFO Bootstrap : Using eth0:10.124.20.63<0>
iZ2ze7iugkwh6c0dul6ed3Z:14094:14094 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
iZ2ze7iugkwh6c0dul6ed3Z:14094:14094 [0] NCCL INFO cudaDriverVersion 11040
NCCL version 2.14.3+cuda11.7
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Failed to open libibverbs.so[.1]
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO NET/Socket : Using [0]eth0:10.124.20.63<0>
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Using network Socket
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 00/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 01/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 02/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 03/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 04/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 05/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 06/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 07/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 08/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 09/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 10/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 11/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 12/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 13/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 14/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 15/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 16/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 17/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 18/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 19/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 20/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 21/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 22/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 23/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 24/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 25/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 26/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 27/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 28/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 29/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 30/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Channel 31/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Connected all rings
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO Connected all trees
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
iZ2ze7iugkwh6c0dul6ed3Z:14094:14147 [0] NCCL INFO comm 0x55a51c5e20b0 rank 0 nranks 1 cudaDev 0 busId 70 - Init COMPLETE
[2023-07-06 16:23:47,791] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.5, git-hash=unknown, git-branch=unknown
[2023-07-06 16:23:47,791] [WARNING] [config_utils.py:69:_process_deprecated_field] Config parameter cpu_offload is deprecated use offload_optimizer instead
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Using network Socket
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 00/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 01/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 02/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 03/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 04/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 05/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 06/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 07/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 08/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 09/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 10/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 11/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 12/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 13/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 14/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 15/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 16/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 17/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 18/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 19/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 20/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 21/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 22/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 23/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 24/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 25/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 26/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 27/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 28/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 29/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 30/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Channel 31/32 :    0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Connected all rings
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO Connected all trees
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO 32 coll channels, 32 p2p channels, 32 p2p channels per peer
iZ2ze7iugkwh6c0dul6ed3Z:14094:14151 [0] NCCL INFO comm 0x55a51c623900 rank 0 nranks 1 cudaDev 0 busId 70 - Init COMPLETE
[2023-07-06 16:23:47,874] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py:90: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(FusedAdam, self).__init__(params, defaults)
Installed CUDA version 11.4 does not match the version torch was compiled with 11.7 but since the APIs are compatible, accepting this combination
Using /root/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py38_cu117/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.13315367698669434 seconds
[2023-07-06 16:23:48,327] [INFO] [logging.py:96:log_dist] [Rank 0] Using DeepSpeed Optimizer param name adam as basic optimizer
[2023-07-06 16:23:48,408] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = FusedAdam
[2023-07-06 16:23:48,408] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=FusedAdam type=<class 'deepspeed.ops.adam.fused_adam.FusedAdam'>
[2023-07-06 16:23:48,408] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 1 optimizer
[2023-07-06 16:23:48,408] [INFO] [stage_1_and_2.py:133:__init__] Reduce bucket size 100000000
[2023-07-06 16:23:48,408] [INFO] [stage_1_and_2.py:134:__init__] Allgather bucket size 1000000000
[2023-07-06 16:23:48,408] [INFO] [stage_1_and_2.py:135:__init__] CPU Offload: False
[2023-07-06 16:23:48,408] [INFO] [stage_1_and_2.py:136:__init__] Round robin gradient partitioning: False
Rank: 0 partition count [1, 1] and sizes[(7799803136, False), (2390272, False)] 
[2023-07-06 16:23:54,259] [INFO] [utils.py:785:see_memory_usage] Before initializing optimizer states
[2023-07-06 16:23:54,259] [INFO] [utils.py:786:see_memory_usage] MA 43.6 GB         Max_MA 43.6 GB         CA 43.61 GB         Max_CA 44 GB 
[2023-07-06 16:23:54,259] [INFO] [utils.py:793:see_memory_usage] CPU Virtual Memory:  used = 5.69 GB, percent = 4.6%
Traceback (most recent call last):
  File "finetune_visualglm.py", line 203, in <module>
    training_main(args, model_cls=model, forward_step_function=forward_step, create_dataset_function=create_dataset_function, collate_fn=data_collator)
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 98, in training_main
    model, optimizer = setup_model_untrainable_params_and_optimizer(args, model)
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/sat/training/deepspeed_training.py", line 174, in setup_model_untrainable_params_and_optimizer
    model, optimizer, _, _ = deepspeed.initialize(
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1184, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1419, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 484, in __init__
    self.initialize_optimizer_states()
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 619, in initialize_optimizer_states
    self.optimizer.step()
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/root/miniconda3/envs/visualglm-6b/lib/python3.8/site-packages/deepspeed/ops/adam/fused_adam.py", line 155, in step
    state['exp_avg'] = torch.zeros_like(p.data)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 29.06 GiB (GPU 0; 79.35 GiB total capacity; 72.66 GiB already allocated; 5.65 GiB free; 72.69 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
iZ2ze7iugkwh6c0dul6ed3Z:14094:14148 [0] NCCL INFO [Service thread] Connection closed by localRank 0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14094 [0] NCCL INFO comm 0x55a51c5e20b0 rank 0 nranks 1 cudaDev 0 busId 70 - Abort COMPLETE
iZ2ze7iugkwh6c0dul6ed3Z:14094:14152 [0] NCCL INFO [Service thread] Connection closed by localRank 0
iZ2ze7iugkwh6c0dul6ed3Z:14094:14094 [0] NCCL INFO comm 0x55a51c623900 rank 0 nranks 1 cudaDev 0 busId 70 - Abort COMPLETE

**Comment by 1049451037** [comment]
把程序终止，然后运行nvidia-smi看一下打印出来什么

**Comment by smallhackeryifa** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:00:07.0 Off |                    0 |
| N/A   35C    P0    54W / 400W |      0MiB / 81251MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by 1049451037** [comment]
跑其他pytorch程序正常吗，是不是显卡配置有问题？另外检查一下代码是不是github最新版

**Comment by smallhackeryifa** [comment]
跑其他程序是正常的，代码更新为main分支下的最新版本重试，依然报显存不足的错误

> 跑其他pytorch程序正常吗，是不是显卡配置有问题？另外检查一下代码是不是github最新版

**Comment by 1049451037** [comment]
那跑finetune/finetune_visualglm_lora.sh正常吗？别用qlora试一下
