### ISSUE TITLE
多机多卡微调报错ncclInternalError

### ISSUE THREAD

**Issue by sunxiaoyu12** [THUDM/VisualGLM-6B#203]
微调命令：
`bash  finetune/finetune_visualglm.sh`
代码正常运行到加载模型和tokenizer，之后报错如下：
![image](https://github.com/THUDM/VisualGLM-6B/assets/38753856/4479508e-fa9e-4b71-8c67-999ac2a6f0f0)
打印NCCL具体报错信息如下：
![image](https://github.com/THUDM/VisualGLM-6B/assets/38753856/64505f89-eca9-452f-aaf8-9ad9d5058d60)

![image](https://github.com/THUDM/VisualGLM-6B/assets/38753856/25ac0f75-4ae3-4ee2-bea2-05910ebea050)

请问有人遇到这样的问题嘛？

**Comment by sunxiaoyu12** [comment]
我加了这两个参数
![image](https://github.com/THUDM/VisualGLM-6B/assets/38753856/c6fc615b-e3a5-4f0a-921f-4a3c2b73b5ba)

**Comment by Sleepychord** [comment]
请确定nccl配置和版本的正确性，是否使用了正确的ib等

**Comment by sunxiaoyu12** [comment]
> 请确定nccl配置和版本的正确性，是否使用了正确的ib等
你好，我查看了NCCL的版本，是2.15.2，查看了IB网卡名，显示如下：
![360d72db3af78c9e1c3dd9745c8b45b](https://github.com/THUDM/VisualGLM-6B/assets/38753856/849dd06f-8242-4fea-acc2-8be1d7051d7b)
![ac646d0f8f388b611edc9b9d7551ded](https://github.com/THUDM/VisualGLM-6B/assets/38753856/aa042e79-5722-4959-a07e-d7d6d75a57f1)

请问正确的版本应该是什么？NCCL_IB_DISABLE已经设置为0

**Comment by 1049451037** [comment]
deepspeed多机不是这样指定的，你需要让每个机器知道master_addr是谁

**Comment by sunxiaoyu12** [comment]
> deepspeed多机不是这样指定的，你需要让每个机器知道master_addr是谁，以及master_port也不应该是随机数

我运行DeepSpeedExamples中的例子的时候是成功的（https://github.com/microsoft/DeepSpeedExamples/blob/master/training/HelloDeepSpeed/train_bert_ds.py）

**Comment by sunxiaoyu12** [comment]
问题已解决，是NCCL配置出现问题，缺少socket通信网络设置：
`NCCL_SOCKET_IFNAME=eth0`
在命令行之前加入以下即可：
export NCCL_IB_DISABLE=1; export NCCL_P2P_DISABLE=1; export NCCL_DEBUG=INFO; export NCCL_SOCKET_IFNAME=eth0

**Comment by shituo123456** [comment]
> 问题已解决，是NCCL配置出现问题，缺少socket通信网络设置： `NCCL_SOCKET_IFNAME=eth0` 在命令行之前加入以下即可： export NCCL_IB_DISABLE=1; export NCCL_P2P_DISABLE=1; export NCCL_DEBUG=INFO; export NCCL_SOCKET_IFNAME=eth0

您好，如何在.sh完整添加多卡训练呢，我添加了--num_gpus  --num_nodels  
报错：ValueError: Cannot specify num_nodes/gpus with include/exclude

**Comment by corkiyao** [comment]
> > 问题已解决，是NCCL配置出现问题，缺少socket通信网络设置： `NCCL_SOCKET_IFNAME=eth0` 在命令行之前加入以下即可： export NCCL_IB_DISABLE=1; export NCCL_P2P_DISABLE=1; export NCCL_DEBUG=INFO; export NCCL_SOCKET_IFNAME=eth0
> 
> 您好，如何在.sh完整添加多卡训练呢，我添加了--num_gpus --num_nodels 报错：ValueError: Cannot specify num_nodes/gpus with include/exclude

请问您解决这个问题了吗，我也遇到了这个问题，谢谢。
